services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    user: "www-data" 
    depends_on:
      - queue
    networks:
      - laravel-network

  queue:
    build: .
    command: php artisan queue:work --tries=3
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    user: "www-data" 
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge